class Foil:
    def __ini__(self, input_string: str) -> None: ...
    
    def lift_coefficient(self, angle_of_attack: float) -> float: ...
    def drag_coefficient(self, angle_of_attack: float) -> float: ...